### PR TITLE
[RFR] API freezing — 1.0.0

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Pre 1.0.0 requires two attributes on the toggle:
- `data-a11y-toggle`
- `aria-controls="toggled-id"`

In version 1.0.0, only `data-a11y-toggle` is mandatory, and it is mapped to the toggled ID directly. The script deals with `aria-controls`.

Reasons behind this change:
- it makes the API simpler (one attribute instead of 2)
- it hides the whole ARIA logic inside the script

Ping @ffoodd for review if you don’t mind.

### CODE REVIEW

**Comment by ffoodd** [comment]
Isn't button's `[id]`mandatory too? Or does your script compute it from `data-a11y-toggle` value? I can't find any clue (but I'm reading too fast ><).

This question excepted, this is really better.

**Comment by KittyGiraudel** [comment]
Well, `id` is not mandatory to make it work, although it’s strongly encouraged for `aria-labelledby`. What do you think?

**Comment by ffoodd** [comment]
Just wondering what happens w/wo `[id]` :) 
Already saw scripts failing because of missing value -_-

Also I think you could add an `[id]` if there isn't any for the button, would be easy enough. This shall ensure that `[aria-labelledby]` is always used. Is it overkilling?

Any thought?

**Comment by KittyGiraudel** [comment]
> Just wondering what happens w/wo [id] :) 
> Already saw scripts failing because of missing value -_-

Not `aria-labelledby` gets added.

> Also I think you could add an [id] if there isn't any for the button, would be easy enough. This shall ensure that [aria-labelledby] is always used. Is it overkilling?

It is easy. But when generating attributes, especially unique attributes, you have to make sure never to cause any collision.

**Comment by ffoodd** [comment]
Is this really an issue? You could prefix and suffix your value, as a namespace. Also if the toggling région has an unique id, your generated button id should be unique too.

The real advantage is that data-a11y-toggle stays the only mandatory attribute.

This is only an advice, so if that sounds weird, do not go with that idea. I think it would be better, but you may want another opinion 😊

 I do enjoy your work, this Is very elegantly done 😉

**Comment by KittyGiraudel** [comment]
> The real advantage is that data-a11y-toggle stays the only mandatory attribute.

We could generate it if not present.

**Comment by KittyGiraudel** [comment]
Alright, what do you think now? :)

**Comment by ffoodd** [comment]
This looks perfect to me 👌
Good job.

**Comment by KittyGiraudel** [comment]
Thanks!

**Pull request merged**
